---
- name: Clean up broken Elasticsearch, Kibana, TheHive, and BTWIN-SERVER installation
  hosts: edr_backend
  become: true
  tasks:
    # Elasticsearch cleanup
    - name: Stop Elasticsearch if running
      systemd:
        name: elasticsearch
        state: stopped
      ignore_errors: yes

    - name: Remove Elasticsearch packages
      apt:
        name: elasticsearch
        state: absent
        purge: yes
        autoremove: yes

    - name: Remove Elasticsearch directories
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /etc/elasticsearch
        - /var/lib/elasticsearch
        - /var/log/elasticsearch
        - /usr/share/elasticsearch
      ignore_errors: yes

    - name: Remove apt key
      file:
        path: /etc/apt/keyrings/elastic.gpg
        state: absent
      ignore_errors: yes

    - name: Remove repository
      file:
        path: /etc/apt/sources.list.d/elastic-8.x.list
        state: absent
      ignore_errors: yes

    # Kibana cleanup
    - name: Stop Kibana if running
      systemd:
        name: kibana
        state: stopped
      ignore_errors: yes

    - name: Remove Kibana package
      apt:
        name: kibana
        state: absent
        purge: yes
        autoremove: yes
      ignore_errors: yes

    - name: Remove Kibana directories
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /etc/kibana
        - /var/log/kibana
        - /usr/share/kibana
      ignore_errors: yes

    # TheHive cleanup
    - name: Stop TheHive if running
      systemd:
        name: thehive
        state: stopped
      ignore_errors: yes

    - name: Remove TheHive package
      apt:
        name: thehive
        state: absent
        purge: yes
        autoremove: yes
      ignore_errors: yes

    - name: Remove TheHive directories
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /etc/thehive
        - /var/log/thehive
        - /usr/share/thehive
        - /var/lib/thehive
      ignore_errors: yes

    # BTWIN-SERVER cleanup
    - name: Stop Nginx if running
      systemd:
        name: nginx
        state: stopped
      ignore_errors: yes

    - name: Remove Nginx packages
      apt:
        name: 
          - nginx
          - nginx-common
          - nginx-core
        state: absent
        purge: yes
        autoremove: yes
      ignore_errors: yes

    - name: Remove Nginx directories
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /etc/nginx
        - /var/log/nginx
        - /var/www/html
      ignore_errors: yes

    - name: Remove BTWIN-SERVER files
      file:
        path: /srv/btwin-server
        state: absent
      ignore_errors: yes

    - name: Remove BTWIN-SERVER Nginx configuration
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /etc/nginx/sites-available/btwin-server
        - /etc/nginx/sites-enabled/btwin-server.config
      ignore_errors: yes

    # Java cleanup (if not needed by other applications)
    - name: Remove Java packages
      apt:
        name: 
          - openjdk-11-jdk
          - openjdk-11-jre
        state: absent
        purge: yes
        autoremove: yes
      ignore_errors: yes

    # Final cleanup
    - name: Clean up any remaining configuration files
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /etc/elasticsearch
        - /etc/kibana
        - /etc/thehive
        - /etc/nginx
      ignore_errors: yes

    - name: Reload systemd daemon
      systemd:
        daemon_reload: yes 