---
- name: Add TheHive GPG key
  apt_key:
    url: https://raw.githubusercontent.com/TheHive-Project/TheHive/master/PGP-PUBLIC-KEY
    state: present

- name: Ensure keyrings directory exists
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: 0755

- name: Download TheHive GPG key to keyrings
  get_url:
    url: https://raw.githubusercontent.com/TheHive-Project/TheHive/master/PGP-PUBLIC-KEY
    dest: /etc/apt/keyrings/thehive.gpg
    mode: '0644'

- name: Add TheHive repository (new keyring method)
  apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/thehive.gpg] https://deb.thehive-project.org release main"
    state: present
    filename: thehive

- name: Update apt cache
  apt:
    update_cache: yes

- name: Try to install TheHive from repo
  apt:
    name: thehive
    state: present
  register: thehive_install
  ignore_errors: yes

- name: Download TheHive .deb if repo install failed
  get_url:
    url: https://github.com/TheHive-Project/TheHive/releases/download/5.2.4/thehive_5.2.4-1_all.deb
    dest: /tmp/thehive.deb
  when: thehive_install is failed

- name: Install TheHive from .deb if repo install failed
  apt:
    deb: /tmp/thehive.deb
  when: thehive_install is failed

- name: Create certs directory
  file:
    path: /etc/thehive/certs
    state: directory
    owner: root
    group: thehive
    mode: 0750

- name: Copy CA cert from Elasticsearch
  copy:
    src: /etc/elasticsearch/certs/ca.crt
    dest: /etc/thehive/certs/ca.crt
    remote_src: yes
    owner: root
    group: thehive
    mode: 0644

- name: Generate TheHive private key
  command: openssl genrsa -out /etc/thehive/certs/thehive.key 4096
  args:
    creates: /etc/thehive/certs/thehive.key

- name: Generate TheHive CSR
  command: openssl req -new -key /etc/thehive/certs/thehive.key -subj "/CN={{ ansible_fqdn | default(ansible_hostname) }}" -out /etc/thehive/certs/thehive.csr
  args:
    creates: /etc/thehive/certs/thehive.csr

- name: Sign TheHive certificate with CA
  command: openssl x509 -req -in /etc/thehive/certs/thehive.csr -CA /etc/thehive/certs/ca.crt -CAkey /etc/elasticsearch/certs/ca.key -CAcreateserial -out /etc/thehive/certs/thehive.crt -days 365 -sha256
  args:
    creates: /etc/thehive/certs/thehive.crt

- name: Create PKCS12 keystore for TheHive
  command: >
    openssl pkcs12 -export
    -in /etc/thehive/certs/thehive.crt
    -inkey /etc/thehive/certs/thehive.key
    -certfile /etc/thehive/certs/ca.crt
    -out /etc/thehive/certs/thehive.p12
    -password pass:thehivepass
  args:
    creates: /etc/thehive/certs/thehive.p12

- name: Set permissions on certs
  file:
    path: /etc/thehive/certs
    owner: root
    group: thehive
    mode: 0750
    recurse: yes

- name: Configure TheHive
  template:
    src: thehive.conf.j2
    dest: /etc/thehive/application.conf
    owner: root
    group: thehive
    mode: 0660
  notify: restart thehive

- name: Start and enable service
  systemd:
    name: thehive
    state: started
    enabled: yes 