---
- name: Install Kibana
  apt:
    name: kibana
    state: present
    update_cache: yes

- name: Create certs directory
  file:
    path: /etc/kibana/certs
    state: directory
    owner: root
    group: kibana
    mode: 0750

- name: Copy CA cert from Elasticsearch
  copy:
    src: /etc/elasticsearch/certs/ca.crt
    dest: /etc/kibana/certs/ca.crt
    remote_src: yes
    owner: root
    group: kibana
    mode: 0644

- name: Generate Kibana private key
  command: openssl genrsa -out /etc/kibana/certs/kibana.key 4096
  args:
    creates: /etc/kibana/certs/kibana.key

- name: Generate Kibana CSR
  command: openssl req -new -key /etc/kibana/certs/kibana.key -subj "/CN={{ ansible_fqdn | default(ansible_hostname) }}" -out /etc/kibana/certs/kibana.csr
  args:
    creates: /etc/kibana/certs/kibana.csr

- name: Sign Kibana certificate with CA
  command: openssl x509 -req -in /etc/kibana/certs/kibana.csr -CA /etc/kibana/certs/ca.crt -CAkey /etc/elasticsearch/certs/ca.key -CAcreateserial -out /etc/kibana/certs/kibana.crt -days 365 -sha256
  args:
    creates: /etc/kibana/certs/kibana.crt

- name: Set permissions on certs
  file:
    path: /etc/kibana/certs
    owner: root
    group: kibana
    mode: 0750
    recurse: yes

- name: Set elastic password for Kibana
  set_fact:
    elastic_password: "{{ hostvars[inventory_hostname].elastic_auto_password | default('') }}"

- name: Configure Kibana
  template:
    src: kibana.yml.j2
    dest: /etc/kibana/kibana.yml
    owner: root
    group: kibana
    mode: 0660
  notify: restart kibana

- name: Ensure curl is installed
  apt:
    name: curl
    state: present

- name: Start and enable service
  systemd:
    name: kibana
    state: started
    enabled: yes
  register: kibana_start_result
  failed_when: false

- name: Check Kibana status if startup failed
  shell: systemctl status kibana
  register: kibana_status_output
  when: kibana_start_result is failed
  failed_when: false

- name: Display Kibana status if failed
  debug:
    msg: "{{ kibana_status_output.stdout_lines }}"
  when: kibana_start_result is failed

- name: Check Kibana logs if startup failed
  shell: |
    if [ -f /var/log/kibana/kibana.log ]; then
      tail -50 /var/log/kibana/kibana.log
    else
      echo 'No Kibana log file found.'
    fi
  register: kibana_logs_output
  when: kibana_start_result is failed
  failed_when: false

- name: Display Kibana logs if failed
  debug:
    msg: "{{ kibana_logs_output.stdout_lines }}"
  when: kibana_start_result is failed

- name: Fail with clear error message
  fail:
    msg: |
      Kibana failed to start. Check the logs above for the specific error.
      Common causes: config file errors, missing dependencies, permissions, or Elasticsearch not running.
      See the README for troubleshooting steps.
  when: kibana_start_result is failed 